### ISSUE TITLE
How to join the Microsoft Docs organization

### ISSUE THREAD

**Issue by chenjd** [MicrosoftDocs/xamarin-docs.zh-cn#25]
Hi guys,
How to join the Microsoft Docs organization? Is there a guide or documentation?
Thanks~

**Comment by LisandroSu** [comment]
Hello, @chenjd 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
