### ISSUE TITLE
The blue title and the dropdown control

### ISSUE THREAD

**Issue by 8246sasuke** [MicrosoftDocs/xamarin-docs.zh-cn#29]
Can the blue title's visiable and the dropdown control's visiable property sets hidden?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 710e69e5-df3b-c83e-2731-941de51279b5
* Version Independent ID: a4024124-4809-9031-2b3b-e122c765bb4d
* Content: [WPF 平台安装程序 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/platform/wpf)
* Content Source: [docs/xamarin-forms/platform/wpf.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/xamarin-forms/platform/wpf.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hello, @8246sasuke 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by 8246sasuke** [comment]
Hello,@CeciAc
Can the blue area at the top of the form be removed or hidden after the xamarin. WPF project is running?

**Comment by CeciAc** [comment]
Hello, @8246sasuke 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

@JasonCard FYI
