### ISSUE TITLE
无DeviceDisplay.ScreenMetrics属性

### ISSUE THREAD

**Issue by Kim99** [MicrosoftDocs/xamarin-docs.zh-cn#31]
Xamarin.Essentials1.0版没有DeviceDisplay.ScreenMetrics了

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: baaf5be9-c6c2-5c43-c131-6cb01cda6502
* Version Independent ID: 7020d1c9-9b6b-18af-72b9-3e75c0c26340
* Content: [Xamarin.Essentials：设备显示信息 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/essentials/device-display?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/device-display.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/essentials/device-display.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1225](https://github.com/MicrosoftDocs/xamarin-docs/issues/1225) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #1226](https://github.com/MicrosoftDocs/xamarin-docs/issues/1226) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@Kim99

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/xamarin-docs/issues/1225。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
