### ISSUE TITLE
can't find Universal MonoGame Mobile application option

### ISSUE THREAD

**Issue by GamerBin** [MicrosoftDocs/xamarin-docs.zh-cn#32]
The plugin installed in Gallrey is MonoGame Extension 3.7.0.1, but can't find Universal MonoGame Mobile application option on create project.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c8cfc5a0-b571-ef2c-b673-ce197dbfadb5
* Version Independent ID: db506a39-5ba0-4c30-4192-bec75e724fe6
* Content: [第 1 部分 – 创建跨平台 MonoGame - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/graphics-games/monogame/introduction/part1)
* Content Source: [docs/graphics-games/monogame/introduction/part1.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/graphics-games/monogame/introduction/part1.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by LisandroSu** [comment]
Hello, @GamerBin 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
