### ISSUE TITLE
 How to bind click/ItemTap events？

### ISSUE THREAD

**Issue by xxyuze** [MicrosoftDocs/xamarin-docs.zh-cn#43]
CollectionView 
How to bind click/ItemTap events？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1b7cdc65-603d-3f71-fbb0-d388374593d2
* Version Independent ID: 0c7a8507-4dfd-b5ed-4ba2-957623d7198c
* Content: [Xamarin.Forms 之间导航 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/user-interface/collectionview)
* Content Source: [docs/xamarin-forms/user-interface/collectionview.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/xamarin-forms/user-interface/collectionview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
你好，@xxyuze
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by xxyuze** [comment]
文档缺少对事件的说明
