### ISSUE TITLE
How renderers implement Native control's function?

### ISSUE THREAD

**Issue by yelinzh** [MicrosoftDocs/xamarin-docs.zh-cn#45]
Xamarin.Forms renderer is different from platform Native control . How to implement the function of Native control on renderer.
For example, this way creating FrameworkElement instead of Grid, I am missing important functionality like "reveal" on an UI item. XY focus navigation and interaction using gamepad on Xbox. they seem to be not possible or difficult using xamarin.forms.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cfee594b-8ecc-0d4d-9384-e4afe792b3dd
* Version Independent ID: 9957d9e1-1ebc-aadb-90bb-5e80b595bade
* Content: [呈现器基类和本机控件 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback/提供产品反馈" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
