### ISSUE TITLE
不使用 Segue 进行导航的实例代码有问题

### ISSUE THREAD

**Issue by tuoluofu** [MicrosoftDocs/xamarin-docs.zh-cn#47]
不使用 Segue 进行导航的标题下的代码在进行复制后编译装到本机运行报错。
 CallHistoryController callHistory = this.Storyboard.InstantiateViewController("CallHistoryController") as CallHistoryController;
报错内容如下：
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Storyboard (&lt;UIStoryboard: 0x17426fd00&gt;) doesn't contain a view controller with identifier 'CallHistoryController'
Native stack trace:

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f960f02f-b51e-fa98-a74c-a842518510a2
* Version Independent ID: be0af449-b28c-1042-fe1a-1c9a21d2d170
* Content: [Hello，iOS 多屏显示 - 深入了解 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive#feedback)
* Content Source: [docs/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by CeciAc** [comment]
你好，@tuoluofu
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by bizhihai** [comment]
我也遇到同样的问题，在visual studio 2019 for mac + XCode，mac上运行，一样的异常。是不是微软没跟上苹果的更新啊。如果这么低层的应用就报错了，Xamarin根本没法用下去啊。第二个示例就出错了，还搞个屁……
