### ISSUE TITLE
多台windows 连接同一台mac生成问题

### ISSUE THREAD

**Issue by AssassinCode** [MicrosoftDocs/xamarin-docs.zh-cn#48]
单一连接时正常生成，多人连接无法生成

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 992a68e4-2f19-9cb5-d3b6-4f682ee8a1f4
* Version Independent ID: 61923335-63c3-cc42-f310-eb090e09497b
* Content: [Xamarin.iOS 生成主机连接疑难解答 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting#feedback)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/troubleshooting.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by CeciAc** [comment]
你好，@AssassinCode
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@AssassinCode
我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@AssassinCode
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
