### ISSUE TITLE
在Bingding过程中生成了扩展方法，扩展方法的参数的类型的命名空间报错——补充疑难问题

### ISSUE THREAD

**Issue by mingchar** [MicrosoftDocs/xamarin-docs.zh-cn#49]
就是这样的情况：AAA命名空间中有Att类型，在这个命名空间中有一个自动生成的扩展方法Akk,里面的要对Att类型扩展，签名是：Akk(this AAA.Att)。结果报错 不存在AAA命名空间。 就是，自己命名空间中，写自己的全路径报错。  经过尝试，发现以上方法无法解决此问题。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 60db43f9-ecf5-a8d9-df81-cda370c09435
* Version Independent ID: 66de7447-bef5-6f81-a063-23ebee7d01d8
* Content: [绑定疑难解答 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/android/platform/binding-java-library/troubleshooting-bindings#feedback)
* Content Source: [docs/android/platform/binding-java-library/troubleshooting-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/android/platform/binding-java-library/troubleshooting-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
你好，@mingchar
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
