### ISSUE TITLE
2019 preview版本中,Xamarin.LiveReload 不起作用

### ISSUE THREAD

**Issue by wangyankun33** [MicrosoftDocs/xamarin-docs.zh-cn#50]
2019 preview版本中,Xamarin.LiveReload 不起作用

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Xamarin 实时重新加载 （预览版） - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/xaml/live-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by srvbpigh** [comment]
Hello, @wangyankun33
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@wangyankun33
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
