### ISSUE TITLE
不知道意义的文字

### ISSUE THREAD

**Issue by isKevinTrue** [MicrosoftDocs/xamarin-docs.zh-cn#57]
文中有如下不知意义的文字

 > @ no__t @ no__t @ no__t @ no__t @，

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e0301dd5-7ff9-6f2b-ab83-271b539d46fd
* Version Independent ID: fee54cf8-4cc4-de5d-b00d-302d307545fa
* Content: [Android 10 功能 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/android/platform/android-10#feedback)
* Content Source: [docs/android/platform/android-10.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/android/platform/android-10.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by srvbpigh** [comment]
Hello, @isKevinTrue
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@isKevinTrue
感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：XXX。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
