### ISSUE TITLE
Content errata

### ISSUE THREAD

**Issue by x740073529** [MicrosoftDocs/xamarin-docs.zh-cn#59]
At "使用 Visual Studio 更新应用" Section In the second "双击 " app.config " 以将其打开。", Should be  Double click app..xaml

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 46228c67-1dc9-99e0-d279-ff6e722bfd5e
* Version Independent ID: 41994570-80f8-55ae-9a31-9696610b2353
* Content: [设计跨平台的 Xamarin.Forms 应用程序 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/get-started/quickstarts/styling?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/styling.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/get-started/quickstarts/styling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @x740073529
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @x740073529
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/xamarin/get-started/quickstarts/styling?pivots=windows

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
