### ISSUE TITLE
Chinese translate version still got problem of the "Click app.config"

### ISSUE THREAD

**Issue by simplerjiang** [MicrosoftDocs/xamarin-docs.zh-cn#60]
at Chinese machine translate version , Visual Studio macOS tuition version.
the Click app.XAML still is app.config.
It's OK in English version or Visual Studio version.

**Comment by simplerjiang** [comment]
在Solution Pad的 "注释" 项目中，双击 " app.config " 以打开它。 然后，将现有代码替换为以下代码：

**Comment by srvbpigh** [comment]
Hello, @simplerjiang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @simplerjiang 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. **Can you please provide the URL where you found this issue?**
 
Kind regards,
Microsoft DOCS International Team

**Comment by simplerjiang** [comment]
Sorry @CeciAc 
I forgot to post the link.
Here is the link https://docs.microsoft.com/zh-cn/xamarin/get-started/quickstarts/styling?pivots=macos

At "使用 Visual Studio for Mac 更新应用“ , Update the app with Visual Studio for Mac Section

Second Point 
"在Solution Pad的 "注释" 项目中，双击 " app.config " 以打开它。 然后，将现有代码替换为以下代码："

**Comment by CeciAc** [comment]
Hello, @simplerjiang 

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/xamarin/get-started/quickstarts/styling?pivots=macos  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
