### ISSUE TITLE
如何实现选中效果？

### ISSUE THREAD

**Issue by xmu-Jiang** [MicrosoftDocs/xamarin-docs.zh-cn#64]
ListView中Item如何实现选中效果？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be10b84e-1773-7f4c-bd91-2fee1671b284
* Version Independent ID: 26d2aea5-4bcd-c20a-eeab-2537cf7ca78c
* Content: [自定义 ListView 的外观 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/android/user-interface/layouts/list-view/customizing-appearance#feedback)
* Content Source: [docs/android/user-interface/layouts/list-view/customizing-appearance.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/android/user-interface/layouts/list-view/customizing-appearance.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @xmu-Jiang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2711](https://github.com/MicrosoftDocs/xamarin-docs/issues/2711) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@xmu-Jiang 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/xamarin-docs/issues/2711。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
