### ISSUE TITLE
binding

### ISSUE THREAD

**Issue by suhe0919** [MicrosoftDocs/xamarin-docs.zh-cn#65]
太费劲了.,刚开始学习使用 xamrain 感觉非常好 因为 他有xaml 的 UI 语法,还能通用化.但问题来了 再IOS binding 类库项目时 问题太多了,能否优化到 像我们用 .net 的其他项目那样 系统 .a.及header 或者 .Framework 就可以生成 DLL 毕竟用它为了方便快捷 但是 第三方库的binding 让人反感.厌恶.希望能解决

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 526c2ade-756b-6dab-b667-63dab853cae1
* Version Independent ID: 52f56395-f7b3-0512-e24e-f23eddc16d6f
* Content: [Xamarin.iOS 入门 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/ios/get-started/#feedback)
* Content Source: [docs/ios/get-started/index.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/ios/get-started/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by srvbpigh** [comment]
Hello, @suhe0919
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2805](https://github.com/MicrosoftDocs/xamarin-docs/issues/2805) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@suhe0919 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/xamarin-docs/issues/2805。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team

**Comment by LazyCoderSuhe** [comment]
非常感谢 您的返馈.我信心满满的期待中
