### ISSUE TITLE
为什么没有UWP 的案例

### ISSUE THREAD

**Issue by Wowitt** [MicrosoftDocs/xamarin-docs.zh-cn#66]
为什么没有UWP 程序的Image 使用案例？
希望得到回复！Thanks

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 679634c0-a0c6-cc03-c50f-6d22ce71c099
* Version Independent ID: 874062b9-a51b-a10d-4d27-d3811fa9b56b
* Content: [Xamarin.Forms 图像教程 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/get-started/tutorials/image/?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/image/index.yml](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/get-started/tutorials/image/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @Wowitt
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2847](https://github.com/MicrosoftDocs/xamarin-docs/issues/2847) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@Wowitt 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/xamarin-docs/issues/2847。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
