### ISSUE TITLE
"Xamarin。窗体" should be "Xamarin.Forms"

### ISSUE THREAD

**Issue by tony-xia** [MicrosoftDocs/xamarin-docs.zh-cn#72]
"Xamarin。窗体" should be "Xamarin.Forms"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e2aa5fc1-2b9b-9610-77b2-06bb9eeb1ed1
* Version Independent ID: 8a3da39b-d2a7-27f5-eee9-20842a18519b
* Content: [Xamarin. Forms SearchBar - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/user-interface/searchbar)
* Content Source: [docs/xamarin-forms/user-interface/searchbar.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/xamarin-forms/user-interface/searchbar.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by srvbpigh** [comment]
Hello, @tony-xia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello @tony-xia : 

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 
Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
Hi @tony-xia 

Thank you for your feedback.
We're following up to fix this over-localization issue in all files.

Best regards,
Jason
