### ISSUE TITLE
是否可以支持中文？

### ISSUE THREAD

**Issue by jonny-xhl** [MicrosoftDocs/xamarin-docs.zh-cn#77]
[在此处输入反馈]
我进行了demo测试，输入`English`是没问题的,但是我将`text`输入成`chinese`就没有效果。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c941b98c-cfe4-a6c9-2117-f5f0d2f5a7f8
* Version Independent ID: 7fe2d995-09dd-2dce-2dbf-7f49e6d7c3f1
* Content: [Xamarin.Essentials：文本到语音转换 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/essentials/text-to-speech?context=xamarin/android)
* Content Source: [docs/essentials/text-to-speech.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/essentials/text-to-speech.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by srvbpigh** [comment]
你好，@jonny-xhl，

我们正在改进我们的内部流程和工程管道。遗憾的是，这会导致我们延迟处理你的反馈。

非常感谢你为我们的文章贡献内容，我们期待继续获取你的支持和理解。

**Comment by jonny-xhl** [comment]
> 你好，@jonny-xhl，
> 
> 我们正在改进我们的内部流程和工程管道。遗憾的是，这会导致我们延迟处理你的反馈。
> 
> 非常感谢你为我们的文章贡献内容，我们期待继续获取你的支持和理解。

ok,Thinks.
