### ISSUE TITLE
visual studio 2017 for mac 不支持此布局方式

### ISSUE THREAD

**Issue by liaokaime** [MicrosoftDocs/xamarin-docs.zh-cn#8]
当我写"&lt;fle"时，visual studio不会提示我"flexlayout"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b954b795-b38e-61ff-3ba1-26a0623b97e6
* Version Independent ID: 65795b50-24d3-1997-038e-ffdb609eb20b
* Content: [Xamarin.Forms FlexLayout - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/user-interface/layouts/flex-layout)
* Content Source: [docs/xamarin-forms/user-interface/layouts/flex-layout.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/xamarin-forms/user-interface/layouts/flex-layout.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by LisandroSu** [comment]
你好，@liaokaime

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
